# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_forgot_password_request:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::request

app_check_email:
    path: /reset-password/check-email
    controller: App\Controller\ResetPasswordController::checkEmail

app_reset_password:
    path: /reset-password/reset/{token}
    controller: App\Controller\ResetPasswordController::reset
